### ISSUE TITLE
FVGQ_1_kalman has odd behavior and never executes more than twice?

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#12]
You can try the verison in the unit tests:
```julia
HMCExamples.main_FVGQ_1_kalman(["--num_samples", "50", "--print_level", "3"])
```

With this, it seems to be compiling and even generating the derivative code, but with the first two evalutions (which you can see with the new `--print_level`) you will see the output as:
```julia
[ Info: Generating 50 samples with 5 adapts
θ = [0.9647899940949041, 0.8377289007165197, 1.0, 4.693919621882787, 0.2647210865958253, 0.2922503642379483, 0.23395829009257788, 0.13814379137082347, 0.08774539697383191, 1.371588946385065, 1.0663836446440518, 0.584978849278624, 0.5392086182763559, 0.2769069070787606, 0.8375602673849991, 0.26398705206909406, 1.8622653016597435, 1.3546587524454503, 4.362803427872362, 6.496075429504712, 2.917599911655487, 0.8844536558857823, 0.1736819080750675]
θ = [0.9983028850953379, 0.8814, 1.0, 8.4257, 0.2851, 0.7841, 0.8028, 0.6071, 0.0958, 1.4048, 1.0093, 0.7838, 0.9735, 0.9454, 0.4932, 0.0075, 0.1164, 0.0137, 0.0054, 0.0029, 0.0063, 0.0058, 0.0012]
```
It doesn't seem to get past there?

Something that stands out (but might not be a problem) is that the magnitude of some of these near the end of the 2nd sample is completely different than the magnitude of the first one.  Maybe this is exactly the way it should be, or maybe it is having trouble because it is being thrown into a crazy part of the state space?

I would quadruple check the following:
- Are the `FVGQ_1_kalman_defaults.txt` checked carefully against the old implementation?  Especially the `p` and the `p_f` ones?
- Are the prior values carefully checked against the old implementation?
- Are we 100% sure that the `θ` is stacked exactly the same and is aligned with these?  Same with the `p_f`?
- Did we doublecheck that the priors don't have a typo?

Last, there are a few things that we can do:
1. We can add more `print_level > 2` output in the `generate_perturbation`  or even `print_level > 3` for crazy amounts of output.
2. There are a variety of hooks for callbacks in DSSM which we can look at the intermediate results.  These are passed into the perturbation settings constructor.

There are another potential set of issues related to the cache.  But when I run it without any sort of caching I get the same behavior---so I don't think that is the problem.

**Comment by jlperla** [comment]
The other thing that is odd with this example is that I don't see any of the normal output that we would get with the DSSM set to a high print_level?

**Comment by wupeifan** [comment]
>Something that stands out (but might not be a problem) is that the magnitude of some of these near the end of the 2nd sample is completely different than the magnitude of the first one. 

Turing will first use some random number to run the sampler once, and then starting with the initial point we set. The second line is indeed the initial point. Therefore, the behaviors here are normal. @jlperla

**Comment by cpfiffer** [comment]
Yep I agree with this. If the gradient evaluation takes a long time, we'll see this kind of thing all the time. How long did this run before you terminated?

**Comment by jlperla** [comment]
So the first time it runs it would not call with AD and so it would only call the primal... then the second time it would call with the zygote wrapper (at which point it should execute the rrule code)?

**Comment by cpfiffer** [comment]
Yeah, that's correct. It's still stupid slow, though.

**Comment by jlperla** [comment]
Closing for now.  We are going to julia 1.5 until versions are all bumped and can revisit
