### ISSUE TITLE
Add replication code for first-order RBC with stochastic volatility

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#128]
@donskerclass   Should we do this with student-t shocks or gaussian?  Guassian might be a little easier for simulation/etc. so my preference is for that (unless gaussian changes whether this is a useful exercise or not).

I think the tasks are basically the same as #127  but with the different notebook, etc.?  Any additional comments?

**Comment by donskerclass** [comment]
For reference, the notebook is available at 

[Student-t and stochastic volatility](https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/notebooks/NonGaussianRBC.ipynb) 

This again uses exactly the RBC model from the other experiments, but modify the Turing model applied around it.  

Stochastic volatility requires a few new functions that modify/replace DifferenceEquations.jl functions used for analogous steps in the case without stochastic volatility. These are provided in the notebook. I wrote them in a bespoke and very non-generic manner, allowing for only 1-dimensional shocks, as opposed to general, and did not write any custom adjoints like we have for the corresponding functions (the default autodiff takes care of it). I suspect this makes the code both slow and fragile. Fortunately, I don't care and neither should you, as we are not advertising a general stochastic volatility feature, so just replicate it as is.

Currently in the notebook, the stochastic volatility example also has student-t shocks. This can be replaced with Gaussian shocks with appropriate modifications to the code: the illustration was there to show that they work together. But a basic version with one at a time may be preferred.
