### ISSUE TITLE
Add replication code for 2nd order RBC with nonlinear adjustment costs

### ISSUE THREAD

**Issue by donskerclass** [HighDimensionalEconLab/HMCExamples.jl#129]
The basic tasks are the same as in Issues #127 and #128 , but now with an RBC modified to have adjustment costs so that nonlinearities matter. Working code is again available in a notebook: the task is to translate it into replicable experiments.

[RBC with nonlinear adjustment costs](https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/MlikotaSchorfheide.ipynb)

The model here is a slightly different RBC model than our original and so requires a new DSSM model compilation/etc. The model details are coming from [Mlikota and Schorfheide's paper](https://bpb-us-w2.wpmucdn.com/web.sas.upenn.edu/dist/e/242/files/2022/11/SMC_MT_v7.pdf), their model 3. 

This should only be estimated at 2nd order joint, as the experiments in the notebook (and some basic analysis of the model) show that the new nonlinearity parameter is not identified when the model is solved at first order, and the HMC sampler performance is bad, but it should be fine at second order at the chosen parameter values (also taken from the M&S paper).

**Comment by jlperla** [comment]
I belive this is complete, so I close it for now.  We can generate sub-issues from it.
