### ISSUE TITLE
Ensure FVGQ Kalman exactly replicates the old repo

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#13]
The key files here are:
- [x] The model file in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/generated_models/FVGQ20_1.jl  is correct (and is executed in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/generate_models.jl#L17-L21 as well)
- [x] The code in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_FVGQ_1_kalman.jl  loads up the data, creates the priors
  - We need to quadruple check that there are no types in the names of the different priors that are loaded, etc. in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_FVGQ_1_kalman.jl#L12-L54
  - Also that the cirrect data file is loaded, etc.
  - https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_FVGQ_1_kalman.jl#L88-L204 has all of the arugment names, which that `kalman_defaults.txt` loaded up as providing the default values for.  They can all be swapped on the commandline
  - Don't forget to verfiy that the nuts sampler parametesr are also being loaded corretly, and have the correct settings in
- [x] https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/FVGQ_1_kalman_defaults.txt  should have all of the priors, initial conditions, settings, etc.  No hardcoded initial conditions anywhere else  of course, we can tweak these on the CLI or in a config file, but the baseline should be what we are running now
  - [x] I think we need to quadruple check the `p` and `p_f` and the related ordering of them in particular
- [x] The data file is in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/data/FVGQ_1.csv
https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_FVGQ_1_kalman.jl#L62-L74
- The implementation of the turing model is in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L81-L123
-[ ] Check that the priors are all loading with the correct names from the `params`, etc. in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L83-L107
- [x] The variablese for the theta are loaded in the exact correct order in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L109
- [ ] The dereending logic is correct in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L118-L119

These should map to the exact version that @wupeifan  is running the 1st order code on.  When in doubt, fix variables in one form or another.

**Comment by wupeifan** [comment]
@cpfiffer Did you and Jan generate the FVGQ model by yourselves, or it is copied from the old repo? This generated file is too large for me to check...

**Comment by jlperla** [comment]
@wupeifan do you mean the generated model or the file which generates it? I may have made a mistake on the file to check for that above. It is https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/FVGQ20.jl


 I think it is important to check that file which generates the model in the deps closely...and we can run it again if we need to make sure it is working. @janrosa1 and @cpfiffer did you generate the file from that code or run something separate? Because we should run that exact file for reproducibility

**Comment by wupeifan** [comment]
> do you mean the generated model or the file which generates it?
Yeah, it was listed as the first item.  I was checking that but that file is just too large.

The source file https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/FVGQ20.jl is identical to that in the old repo, so I don't think there's an issue then.

**Comment by cpfiffer** [comment]
Yeah, all copied from the main repo.

**Comment by jlperla** [comment]
Lets not close this until we have the exact replcition of the model we want to run with the fixed parameters (or whatever it is that we want to run).  @wupeifan  I think that you will probalby need to make the changes yourself on this, but @cpfiffer  can do a verification that it makes sense given that he can now see that other branch of yours.
