### ISSUE TITLE
Verify number of SGU draws for dynare

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#157]
See the `sgu_1.mod` and `sgu_2.mod`.

The orginal code had:
```
%estimation(datafile = '../../data/SGUsimorder1.csv', mode_file = 'SU03ext_mode.mat', order = 1, mh_nblocks = 1, mh_replic = 2000000, mh_drop = 0.1, mh_jscale = 0.01, mode_compute = 0, mcmc_jumping_covariance = identity_matrix);

estimation(datafile = '../../data/SGUsimorder2.csv', mode_file = 'SU03ext_mode.mat', order = 2, mh_nblocks = 1, mh_replic = 100000, mh_drop = 0.1, mh_jscale = 0.01, mode_compute = 0, mcmc_jumping_covariance = identity_matrix, number_of_particles = 60000, nonlinear_filter_initialization=3);
```
which has been copied over.  I have left those as-is for now, but we should revisit before generating the final results

**Comment by donskerclass** [comment]
These are consistent with our previous code, but the order 1 value not consistent with values reported in the paper. Specifically, the paper claims 135000 draws at first order with 135000 discarded, while this has 200k with 10% discarded. 

I'm not sure which is source of difference, but comparing the previous table code to the previous simulation code, the table had hardcoded values, so I suspect that was inconsistent. We should double check all timing results in the SGU Dynare tables too, which were also hardcoded: possibly the results refer to an earlier run. The current table code no longer hardcodes these. It is not clear if summary stats and figures come from that earlier run or the more recent larger one.

I have no objection to moving to 200k as the source of all SGU1 stats.

Anyway, all of that is to say that the current code looks fine, but we will need to adjust the paper text to reflect the new results (which we will need to do anyway).

**Comment by jlperla** [comment]
@donskerclass  I mostly converted over the old code and perhaps made a few things consistent (though could have made a mistake).  Happy to change to 135000 and run things again.  Whatever you wish.  The stuff in `.replication_results` is all new, including the dynare runs which are run on the same hardware.  Not sure about tables in the paper.

One small thing for the writeup:  If it says something like:
```
--num_samples=10000
--adapts_burnin_prop=0.2
```
Then that is not drawing 10000 and discarding the first 2000 as adaptation, but rather it uses 2000 for adaptation then draws 10000.

There were inconsistencies in the code and paper (and within the code) about the adaptation so I standardized it at `0.2`.  As always, you have the right to modify everything and tell me to rerun things.

**Comment by donskerclass** [comment]
No need to change to 135000, it's probably better with 200000, we just have to make sure the paper is consistent with whatever we did.  And yes, I did make the calculations taking into account that the burn-in proportion is added to the value given in num_samples (and double check the chains themselves to confirm that), so it all looks fine.
