### ISSUE TITLE
Upgrade generated models to new DSSM

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#24]
- [x] Bump the version of DSSM to the latest released version, etc.
- [x] Replace https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/FVGQ20.jl with the correct one in the other repo.  Hoepfully keep it the identical file so we can just copy/paste
- [x] Replace https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/rbc.jl with the correct one from the other repo if it exists, or adapt it if not.  @wupeifan  can help point you in the right direction there.
- [x] Update https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/generate_models.jl to use the new stuff for generating the models.  Follow https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/test/make_perturbation_model.jl#L93-L95  or something similar
- [x] RUn it and verify that it seems to correctly overwrite what is in https://github.com/HighDimensionalEconLab/HMCExamples.jl/tree/main/src/generated_models
- [x] Fix up the includes to get at the new models in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/HMCExamples.jl#L8-L12   Note that now it doesn't generate separate first and second order ones
- [x] See if the package can include them.  I think you can temporarily comment out the https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/HMCExamples.jl#L14-L25  just to check that it actually does load up with an include

**Comment by wupeifan** [comment]
One notice to add here: run with Julia 1.6.

**Comment by wupeifan** [comment]
latest push fixes these
