### ISSUE TITLE
Converting model loading over to new DSSM (without the sequential stuff)

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#25]
After #24 

For each of the model definitions we need to update things.  As an example, the `rbc_joint` is

IN the TuringModels file:
- [x] The `p` in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L45 would turn into a a named tuple and should load from those priors.   Maybe rename it to be `p_d` to make it consistent with the DSSM repo as well.  The `p_f` passed in will become a named tuple itself.  It might be that the following works immediately
```julia
p_d = (;α, β, ρ)
```
and the appropriate one for the `p_f` as well.
- [x] [Modify https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L27](https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L50) to be the correct call to the perturbations with the new `p_d` and `p_f` and the passed in `cache`.
- [ ] Comment out the call to the `solve` in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/turing_models.jl#L36  until we get the sequential working

Then in the actual setup file with the CLI args:
- [x] The https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/rbc_1_joint_defaults.txt#L2-L3  needs to be split up to take these as named args instead for which to create the `p` and `p_f`as named tuples from their arguments.  Use the same name as the prior prefix.  so instead of `--p=[0.2981, 0.1891, 0.9002]` I think it becomes
```
--alpha=0.2981
--beta= 0.9002
--rho=0.1891
--delta=0.025
--sigma=0.01
--Omega_1=0.003162277
```
Or whatever is the correct order.
- [x] Modify the arguments in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_rbc_1_joint.jl#L66-L71  to handle that as well.  So something like
```
"--alpha"
arg_type = Float64
"--beta"
arg_type = Float64
"--rho"
arg_type = Float64
"--delta"
arg_type = Float64
"--sigma"
arg_type = Float64
"--Omega_1"
arg_type = Float64
```
- [x] Before https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_rbc_1_joint.jl#L20-L22 you need to construct the named names.  So something like
```julia
p_f = (δ = d.delta, σ = d.sigma, Ω_1 =d.Omega_1)
p_d = (α = d.alpha, β = d.beta, ρ = d.rho)
```
then it calls the `rbc_joint` with this.
- [x] Change https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_rbc_1_joint.jl#L19  to support the new way of creating the perturbation as in https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/test/first_order_perturbation.jl#L32  etc.
  - You will want to do this after the createion of the `p_d` named tuple above so you can create the cache appropriately (since it uses that as a template for allocations).
- [x] YOu will need to change how the cache is allocated using something like https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/test/first_order_perturbation.jl#L58
- [x] The initial condition will requite splatting out the named tuple values in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/estimate_rbc_1_joint.jl#L40     I think something like
```julia
init_params = [p_d..., ϵ0]
```
should work.

**Comment by wupeifan** [comment]
It seems that the `ArgParse` package cannot parse the vectors correctly, and the tests in `runtests` would deadlock. Need another one to verify. @janrosa1 @cpfiffer

**Comment by jlperla** [comment]
Are you sure? It used to work. Version change?

It might not be very robust though. See https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/utilities.jl#L10

If the types are different (eg accidentally using an integer? Or the spacing is wrong, it could be an issue

**Comment by wupeifan** [comment]
yeah, I tried to print out some debug messages, and the function hangs at the parameter parsing phase.

**Comment by jlperla** [comment]
Did you try a MWE with the vector thing and post for help? Otherwise I am not sure I would jump to blame it... Might be other issues
