### ISSUE TITLE
Unexpected positive definite matrix error

### ISSUE THREAD

**Issue by wupeifan** [HighDimensionalEconLab/HMCExamples.jl#29]
In Kalman filter part we ensured that the covariance matrix be positive definite but there's an error from FVGQ.

**Comment by wupeifan** [comment]
OK, so https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/kalman_track/src/sequence.jl#L141-L144 fixes this because we cannot put a `try-catch` block inside this function. 
Per discussion on slack, we need a `retcode` from the simulation. @cpfiffer

**Comment by cpfiffer** [comment]
Okay, this one needs to go outside the simulation, especially since we can do this `if` check inside the model block.

**Comment by cpfiffer** [comment]
I'll open a PR, gimmie a sec.

**Comment by wupeifan** [comment]
Yeah, we can wait after those merges. Not in a hurry.

**Comment by cpfiffer** [comment]
Added in aace1c8, could you confirm that this is what we're looking for?

**Comment by wupeifan** [comment]
I think at this point it is fine. We might want to add it as `retcode` just like ODEs in DifferentialEquations.
