### ISSUE TITLE
Try out grid and simple hyperparameter sweeps

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/HMCExamples.jl#49]
- [x] I would first make sure that you can run the CLI yourself after cloning this repo on Julia 1.6.5, instantiating it, etc.  The test for now should probably be a short run for the rbc_1_joint case.  So maybe something like the following (where you can mess with the path if you want to).
```bash
julia --project --threads auto -O1 bin/fit_rbc_1_joint.jl --results_path ./results/main_rbc_1_joint --overwrite_results true --num_samples 100
```
- [x] After that, we want to try to see if we can get this working on grid.  It should automatically instantiate the package/manifest in a run, but that might take a LONG time so I wouldn't expect runs to be quick.  The old code for this is something like
```bash
grid run --instance_type t2.xlarge --framework julia --cpus 3 --name rbc-test bin/fit_rbc_1_joint.jl --results_path ./results/main_rbc_1_joint --overwrite_results true --num_samples 100
```
Except that I am not sure exactly what to do wit hthe `results_path` so you migth want to play with it.

  - Note that we can't currently pass in the `-O1` option to grid, so it will be extra slow for larger models, but it would at least let us get going.
  - With that, youi should be able to see the logs with `grid logs rbc-test` or in the CLI.
- [x] See if you can download the results when complete with something like `grid artifacts rbc-test`.

- [x] Finally, if that works then we want to try a minimal hyperparameter sweep and ensure we can download all the results.  Mabye something like
```bash
grid run --instance_type t2.xlarge --framework julia --cpus 3 --name rbc-test bin/fit_rbc_1_joint.jl --results_path ./results/main_rbc_1_joint --overwrite_results true --num_samples 1000 --max_depth "[3, 4, 5]"
```
or whatever the notation is to try out the different `max_depth` variations as a sweep.  Then make sure we can download all of the results.  See https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/src/rbc_1_joint_defaults.txt  for the default CLI arguments, for example.

If you are having trouble, we can ask for help on the grid slack channel.  Julia is a new feature and might have issues.

**Comment by jbrightuniverse** [comment]
@jlperla All of the above work properly with no issues to report except for the bug we are already aware of with artifact downloading requiring appending e.g. `-exp0` to the end of the run name (and so on for other experiments).

I did observe that one of the experiments (max_depth = 4) in the last run terminated much faster than the rest:
![image](https://user-images.githubusercontent.com/30967260/150610178-1134ffc2-a5df-4eca-9f23-4f62cd4b53ef.png)
I'm not familiar with the mechanics so I'm unsure if that was supposed to happen, but all results are downloadable and present (grid is able to automatically detect new folders so no matter where we specify results to go, they will be logged).

**Comment by jlperla** [comment]
How long does that take on your laptop?  Seems pretty slow, but maybe it is a zygote thing.
